clone_depth: 5

version: "{build}"

environment:
  PLATFORM: x64
  matrix:
    - NODEJS_VERSION: "6"
    - NODEJS_VERSION: "8"
    - NODEJS_VERSION: "10"
    - NODEJS_VERSION: "12"

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
  - npm install # switch to `npm ci` when Node 6 is gone

test_script:
  - node --version
  - npm --version
  - npm test

build: off

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm-cache\ -> appveyor.yml,package.json,package-lock.json'
  - 'node_modules -> appveyor.yml,package.json,package-lock.json' # remove this when Node 6 is gone
